### ISSUE TITLE
Failed to withdraw RAY from sollet to FTX using SPL

### ISSUE THREAD

**Issue by Dr4nk0** [project-serum/spl-token-wallet#206] opened 2021-04-26 21:48 UTC
Hi, everything is in the title.

The error i get is the following : failed to send transaction: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.

Wallet id : https://explorer.solana.com/address/HnZ6KYwFHxeqaPee8sakyKpCzs6ozU8QGnepwX1KJ6UE

Regards

**Comment by armaniferrante** [comment] 2021-04-26 21:57
The problem is that you have zero SOL in your account. Add some SOL and the withdraw will work. Closing.

**Closed by armaniferrante** 2021-04-26 21:57 UTC

**Comment by Dr4nk0** [comment] 2021-04-26 22:06
okay thanks
