### ISSUE TITLE
Used Sollet to convert USDC to erc20 via metamask - Loss money

### ISSUE THREAD

**Issue by Maily74** [project-serum/spl-token-wallet#205] opened 2021-04-26 19:34 UTC
Hello,

I used the send option with ERC20 USDC. Then the wallet asked me if i wanted to convert theses USDC to ERC20 using metamask.
I said yes and sent them. Then nothing happened. 
I had a balance of 4800 usdc approximatively, and now, the balance is 0, and i can t find my USDC into metamask neither.
I quickly saw a message like "50 block couldn t be mint" or something like that (it disapeared quickly) and that's all.
Can someone help me ?

thanks a lot for your help,

David

**Comment by armaniferrante** [comment] 2021-04-26 21:58
Resolved in discord. The problem is that the user needs to complete the transaction via metamask.

**Closed by armaniferrante** 2021-04-26 21:58 UTC

**Comment by Juul078** [comment] 2021-05-07 20:50
Hi, 

I have the exact same problem, and I do not know how to complete the transaction with metamask.

Thanks in advance for the help,

Julian

**Comment by armaniferrante** [comment] 2021-05-07 22:59
Please join discord for assistance.

**Comment by Juul078** [comment] 2021-05-07 23:22
Where do I find the discord link? Sorry, I really can't find it.

**Comment by armaniferrante** [comment] 2021-05-07 23:24
https://discord.gg/2BBun3V7

**Comment by ibrahim1998104** [comment] 2021-05-19 19:11
> https://discord.gg/2BBun3V7

Hi can you help me i have the same problem i made a silly mistake i think, the discord link is expired

**Comment by ibrahim1998104** [comment] 2021-05-19 19:15
i basically sent my usdc from my sollet wallet to my coinbase pro usd(c) wallet all of it went through but nothing came on coinbase pro when i made the transaction metamsk opened up and i confirmed. not too sure what went wrong can you help @armaniferrante

**Comment by ibrahim1998104** [comment] 2021-05-19 19:22
https://explorer.solana.com/tx/5D53LqAxbkRMq79TAeZKNRxyAHaoTvHRStnP982ZQHDAN3KnpCyDQ79UC5YFKvMcGfgP19KCwiMwV5rkK1WzUBWk   This might help you understand where i went wrong maybe?

**Comment by ibrahim1998104** [comment] 2021-05-19 19:24
> https://explorer.solana.com/tx/5D53LqAxbkRMq79TAeZKNRxyAHaoTvHRStnP982ZQHDAN3KnpCyDQ79UC5YFKvMcGfgP19KCwiMwV5rkK1WzUBWk This might help you understand where i went wrong maybe?

@armaniferrante

**Comment by ELDumet** [comment] 2021-08-19 23:53
> Resolved in discord. The problem is that the user needs to complete the transaction via metamask.

CAN u send the discord link same issue here :( ?
