### ISSUE TITLE
lost the seed word cant reach to sollet wallet

### ISSUE THREAD

**Issue by alskarm** [project-serum/spl-token-wallet#253] opened 2021-05-17 12:42 UTC
i cannot reach to my sollet, cause i didnt save the seed words 

FCxx3zthAAfszh4WUSw
![solana](https://user-images.githubusercontent.com/84208281/118490331-813f9480-b726-11eb-88a0-61d15c5115f1.JPG)
VGKJ8br8XpH6i1bnKf12tGxDY

**Comment by VnceB** [comment] 2021-05-22 14:57
That's a feature, not a bug:

"Your private keys are only stored on your current computer or device. You will need these words to restore your wallet if your browser's storage is cleared or your device is damaged or lost."

**Comment by armaniferrante** [comment] 2021-05-22 17:00
> That's a feature, not a bug:
> 
> "Your private keys are only stored on your current computer or device. You will need these words to restore your wallet if your browser's storage is cleared or your device is damaged or lost."

Correct. This is not a development related issue. Only you can restore your wallet because only you have the seed phrase. Closing.

**Closed by armaniferrante** 2021-05-22 17:00 UTC
