### ISSUE TITLE
Sollet wallet no longer able to import ledget on mac osx big sur

### ISSUE THREAD

**Issue by douggie** [project-serum/spl-token-wallet#278] opened 2021-06-02 23:06 UTC
I was able to import my ledger device into sollet via account->import hardware wallet, however this is no longer working in either fire fox (Version 	89.0/Build ID 	20210527174632) or chrome (Version 91.0.4472.77 (Official Build) (x86_64)) running on mac osx 11.2.3 (20D91). It was working fine until a few hours ago.

**Comment by armaniferrante** [comment] 2021-06-08 06:10
Likely caused by the latest chrome updates that broke web usb. This should be addressed by https://github.com/project-serum/spl-token-wallet/pull/289. Please re-open if not.

**Closed by armaniferrante** 2021-06-08 06:10 UTC
